CREATE TABLE IF NOT EXISTS users (
    Id int NOT NULL AUTO_INCREMENT,
    Name varchar(100) NOT NULL,
    Email varchar(150) NOT NULL UNIQUE,
    Password varchar(255) NOT NULL,
    IsActive boolean NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Id)
);