CREATE TABLE IF NOT EXISTS authors (
    id bigint NOT NULL AUTO_INCREMENT,
    name varchar(100) NOT NULL,
    biography text NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
)